### ISSUE TITLE
sound disappearing

### ISSUE THREAD

**Issue by VladimirMrzv** [dimtpap/obs-pipewire-audio-capture#17] opened 2022-07-17 05:41 UTC
I am streaming video from games. Before i used virtual card from pipewire. Now trying this plugin, but after 3:30 minutes sound disappearing.

https://www.twitch.tv/videos/1533647249?t=0h3m17s
from 3:30 no sound

Trying change input source, but not help. And no indication for sound in mixer.

**Comment by dimtpap** [comment] 2022-07-17 15:29
This may take a while to fix because it's happened to me before but it's very hard to reproduce since it's rare and random. What version of PipeWire are you running?

**Comment by VladimirMrzv** [comment] 2022-07-17 15:37
I am on Ubuntu 22.04
pipewire 0.3.55  from https://launchpad.net/~pipewire-debian/+archive/ubuntu/pipewire-upstream

**Comment by VladimirMrzv** [comment] 2022-07-18 10:09
I can help to reproduce it and save log. Write please how to do it.

**Comment by dimtpap** [comment] 2022-07-18 13:08
What are the outputs of `journalctl -e --user-unit pipewire` and `journalctl -e --user-unit wireplumber`? Also does it occur consistently after a few minutes?

**Comment by dimtpap** [comment] 2022-07-18 13:52
I've had it happen with native programs like Firefox and Discord so Proton/Wine is not related. Whenever you can, run OBS through a terminal using this command `PIPEWIRE_DEBUG=5 PIPEWIRE_LOG=pwlog.txt obs --verbose`. When the sound stops, post the pwlog.txt file, it will be in the directory you ran the command in

**Comment by VladimirMrzv** [comment] 2022-07-18 14:52
my files
[pw-dump.log](https://github.com/dimtpap/obs-pipewire-audio-capture/files/9132920/pw-dump.log)
[pwlog1.txt](https://github.com/dimtpap/obs-pipewire-audio-capture/files/9132921/pwlog1.txt)
[pwlog2.txt](https://github.com/dimtpap/obs-pipewire-audio-capture/files/9132922/pwlog2.txt)

**Comment by dimtpap** [comment] 2022-07-18 15:26
This isn't guaranteed to fix the problem since it's so annoyingly random, but see if [this build](https://github.com/dimtpap/obs-pipewire-audio-capture/files/9133196/linux-pipewire-audio-issue17-1.tar.gz) fixes it. Install it like you would install a regular release, replacing the installed version you have

**Comment by VladimirMrzv** [comment] 2022-07-19 15:06
sad, but not helped

New logs
[pw-dump2.log](https://github.com/dimtpap/obs-pipewire-audio-capture/files/9142328/pw-dump2.log)
[pwlog6.txt](https://github.com/dimtpap/obs-pipewire-audio-capture/files/9142329/pwlog6.txt)
[pwlog5.txt](https://github.com/dimtpap/obs-pipewire-audio-capture/files/9142338/pwlog5.txt)


in file 5, after start no sound and plugin not work

**Comment by VladimirMrzv** [comment] 2022-08-02 13:56
Try on another game and it works 3-4 hours. Maybe something go wrong with Dying Light 2.

**Comment by aeris** [comment] 2022-08-29 08:39
Hello here!
I'm facing the same trouble too. Also using wine but other sounds sources vanish after some time too (firefox & discord already experienced). Will try to generate log on a future session.

**Comment by dimtpap** [comment] 2022-09-04 14:03
Playing around with the properties and taking a look at [PipeWire's source code](https://gitlab.freedesktop.org/pipewire/pipewire/-/blob/01266632384cc4f7e38ef7c287f5f1f7e1a67eae/src/pipewire/context.c#L1096) I could get the stream to not process when ALWAYS_PROCESS was set to true. From some quick and dirty searches on their GitLab it looked like these options just affected which driver the stream was set to follow. Setting both to false hopefully prevents this behavior.
Try [this build from commit 0b895f5](https://github.com/dimtpap/obs-pipewire-audio-capture/files/9484832/linux-pipewire-audio-0b895f5.tar.gz)

**Comment by aeris** [comment] 2022-09-04 14:39
Nice, i will try that soon!

**Comment by VladimirMrzv** [comment] 2022-09-13 18:37
After update pipewire and today plugin it works better, but sound continue disappearing in DayingLight2. Now disappear after 1 hour and 25 minutes, it happened two times - 5 days ago and today.

**Comment by dimtpap** [comment] 2022-10-02 23:22
Let me know if this is happening with PipeWire 0.3.59

**Comment by aeris** [comment] 2022-10-03 08:06
No trouble here since last release and during 4-5h session. Will try it soon with 0.3.59.

**Comment by DonKatsu** [comment] 2022-11-27 12:36
OBS 28.1.2, obs-pipewire-audio-capture 1.0.5, Pipewire 0.3.60 from the Fedora repos
Application Audio Capture with Monster Hunter Rise (wine64-preloader selected) is consistently losing audio. Haven't tried anything else yet.
Here's a log but I likely didn't catch it exactly after it happened.  [pwlog.txt](https://github.com/dimtpap/obs-pipewire-audio-capture/files/10098319/pwlog.txt)

**Comment by dimtpap** [comment] 2022-12-04 13:01
Great news, after narrowing down the issue and (reporting it to PipeWire)[https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/2874] it got (resolved)[https://gitlab.freedesktop.org/pipewire/pipewire/-/commit/5b371048df63e63e1c6d1e85b598e043f3878a1d] rather fast. I'll close this on the next PipeWire release if it's fixed. Thanks everybody for your help!

**Comment by dimtpap** [comment] 2022-12-04 13:08
All good! I'm expecting the fix to be included in the next PipeWire release, 0.3.62

**Closed by dimtpap** 2022-12-04 13:08 UTC

**Comment by luni3359** [comment] 2022-12-04 16:48
Thank you so much! I'm very glad it got solved
